language: scala
scala:
- 2.11.11
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test
jdk:
- oraclejdk8
env:
  global:
  - secure: DXZFGrjXs5CjsmA6q7ye2NRQjhAilz9ySn1cfOGyuMJ54/cdXLyTR/sUW9gqxQGp1PV9tYY2uX1keIR/voYxDfFU5UBZA3rEw9D94kUxJ6x9sRQt6ZA1VQHS8Cal+h+rmbyuovhMD2ZSLLxqSpqZ0mse787TH6NsIuH/+nBKjd8/c+LVUHPJBERbci702YzjfdDqUcz1uCUwbtyajD1kDKd7LyLWzJFjQKn4XPDeba7OqeyOSx+AdqKlZuE6Y+sjEBOVpZ2yWjVAfC8gQ6YzmfcACgUb5laki2qFvrOdqXkbkyAcAYC/fd0IFDyJ0Vcxc7qXGG9XXYfjfpkgikF4o3O8KAyyazfFOMN4cDe1IT+X/sgrdA9LQN4z8WemxPZrx8fU1myN0IPp46Inf7E6CtwKswv1flnA4uSvWn8LIWI02V3lWDfZfSz2yP7VD98gsclZQmNj7kw6bEwWvE6Lvipe0XTR4g71odt3uiaB0tzHRB3eMVzb/RofAE+wlHslb4sMwZZWGfQlBI9wbVYfgkhlK+FD0EheCid+2j6vKSltei3ciQdLpP/13Co7DTA4inT8mCKNWr4pKpq5TpuGFcY2KePBlNbzi6ukdtKCz7oIbrGkYb8KQtKxG5gO53Dz5Vn8gkY21BEpKOG4A355mqrn2eBb6X2pz4YeRSQn+60=
  - secure: UKWWftfK62qL4OiChRgeyjR+g/Mr0pShS7L3k4tYd4xtdOakHt+QwbwW49HVXqvGC9fEu5ZX4f6J4CnKf40kvNGDmNadNY4wSS6b74LfZRShY+M/5x0MezJDpxY1VjpfeRXALp33AtZ8sp8Ot1N4ZxV+L8KnbsB/q7Qey3Wp2A4o+PA69Uu/EtpO+0A4Ib/j9JyRl+b/asiMHrjzlcjeeMMWWJj5l4yvdp+htJY8ZowCl5TopVQUHK0qoxJ9QmcMKNExAkC1viJSQzl0iHu9IXaQAfTEqNeRPYgctePbBRXvZs7uiWfMSRQRncvXizbM8Hi6Uz9FrOxbbVR2ao9uTJ4U3mrXDASQZ17siRQIi5cCB5kJKm9Kj9urdpDpUcIbmAqbelf8IDcAgrJuazLf9GUCYwGxzolF9nVibGamvTGpbM6DaBUC1nQbdlZyFILcWQQhKQ6wekFZbnEM0J21uaSEFc6T5X8/pKox18A8+xOs138W359/gQDKgCQITHvy2OrKbNbTOQsS6D1qWGLsKZJ4VQeHQXkKPcrodRQ5+TQVRCRiajXy11NtkUPjHqdMuND4nvRe0OGATIwxtQb4XtPe+xiGlanzIa8woSDJoD8d3fvykvai5fhjz80lBlQYALtsX1O0pT333YmsJs2M81ErjyJmU4ki/LyYpsxtQT0=

after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt ++$TRAVIS_SCALA_VERSION publish; };'
